// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stivwquniuwkzdmsrkzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0aXZ3cXVuaXV3a3pkbXNya3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NDY0MjIsImV4cCI6MjA1MzEyMjQyMn0.2wIt8e2v-mVlT3UTdqoW2MXUFTjR4m5fAnkSRpxUz6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);